name: guidance_bubbles
description: guidance_bubbles is a small but powerful flutter package that allows you to highlight specific parts of your app to explain them to the user or to show your app new features.
version: 0.0.1
publish_to: 'none'
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: